<?php
// app/Http/Controllers/BackupController.php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Response;

use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;

class BackupController extends Controller
{
    public function exportDatabase()
    {
        try {
            // Check if user is authenticated
            if (!Auth::check()) {
                return response()->json([
                    'success' => false,
                    'message' => 'User tidak terautentikasi'
                ], 401);
            }

            $user = Auth::user();

            // Cek jika user adalah super admin
            if ($user->role !== 'super admin') {
                return response()->json([
                    'success' => false,
                    'message' => 'Hanya Super Admin yang dapat melakukan backup database'
                ], 403);
            }

            $database = config('database.connections.mysql.database');
            $timestamp = Carbon::now()->format('Y-m-d_H-i-s');
            $filename = "backup_{$database}_{$timestamp}.sql";

            // Generate SQL content
            $sqlContent = $this->generateBackup();

            // Return response sebagai file download
            return Response::make($sqlContent, 200, [
                'Content-Type' => 'application/sql',
                'Content-Disposition' => 'attachment; filename="' . $filename . '"',
                'Content-Length' => strlen($sqlContent),
            ]);

        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Terjadi kesalahan saat backup database',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    private function generateBackup()
    {
        $database = config('database.connections.mysql.database');
        $user = Auth::user();

        $output = "-- Database Backup Generated on " . Carbon::now()->toDateTimeString() . "\n";
        $output .= "-- Database: {$database}\n";
        $output .= "-- Generated by: " . ($user->nama ?? $user->name ?? 'Unknown') . "\n\n";

        // Rest of your backup generation code remains the same...
        $output .= "SET FOREIGN_KEY_CHECKS=0;\n";
        $output .= "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n";
        $output .= "SET AUTOCOMMIT = 0;\n";
        $output .= "START TRANSACTION;\n";
        $output .= "SET time_zone = \"+00:00\";\n\n";

        // Get all tables
        $tables = DB::select('SHOW TABLES');

        foreach ($tables as $table) {
            $tableName = $table->{'Tables_in_' . $database};

            // Drop table if exists
            $output .= "DROP TABLE IF EXISTS `{$tableName}`;\n";

            // Get create table statement
            $createTable = DB::select("SHOW CREATE TABLE `{$tableName}`")[0];
            $output .= $createTable->{'Create Table'} . ";\n\n";

            // Get table data
            $rows = DB::table($tableName)->get();

            if ($rows->count() > 0) {
                $output .= "-- Data for table: {$tableName}\n";
                $output .= "INSERT INTO `{$tableName}` VALUES\n";

                $insertStatements = [];
                foreach ($rows as $row) {
                    $values = [];
                    foreach ((array)$row as $value) {
                        if ($value === null) {
                            $values[] = 'NULL';
                        } else {
                            $values[] = "'" . addslashes($value) . "'";
                        }
                    }
                    $insertStatements[] = "(" . implode(', ', $values) . ")";
                }

                $output .= implode(",\n", $insertStatements) . ";\n\n";
            }
        }

        $output .= "SET FOREIGN_KEY_CHECKS=1;\n";
        $output .= "COMMIT;\n";

        return $output;
    }

    public function exportDatabaseWithMysqldump()
    {
        try {
            // Check if user is authenticated
            if (!Auth::check()) {
                return response()->json([
                    'success' => false,
                    'message' => 'User tidak terautentikasi'
                ], 401);
            }

            $user = Auth::user();

            if ($user->role !== 'super admin') {
                return response()->json([
                    'success' => false,
                    'message' => 'Hanya Super Admin yang dapat melakukan backup database'
                ], 403);
            }

            $database = config('database.connections.mysql.database');
            $username = config('database.connections.mysql.username');
            $password = config('database.connections.mysql.password');
            $host = config('database.connections.mysql.host');

            $timestamp = Carbon::now()->format('Y-m-d_H-i-s');
            $filename = "backup_{$database}_{$timestamp}.sql";
            $backupPath = storage_path("app/backups/{$filename}");

            // Pastikan folder exists
            if (!file_exists(storage_path('app/backups'))) {
                mkdir(storage_path('app/backups'), 0755, true);
            }

            // Build mysqldump command (more secure way)
            $command = "mysqldump --host={$host} --user={$username} --password={$password} {$database} > \"{$backupPath}\" 2>&1";

            // Execute command
            exec($command, $output, $returnVar);

            if ($returnVar !== 0) {
                throw new \Exception('Gagal menjalankan mysqldump: ' . implode('\n', $output));
            }

            // Check if file was created
            if (!file_exists($backupPath)) {
                throw new \Exception('File backup tidak berhasil dibuat');
            }

            // Download file
            return response()->download($backupPath)->deleteFileAfterSend(true);

        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Terjadi kesalahan saat backup database',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
