<?php
// app/Http/Controllers/BackupController.php

namespace App\Http\Controllers;

use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Validator;

class BackupController extends Controller
{
    public function exportDatabase()
    {
        try {
            // Check if user is authenticated
            if (!Auth::check()) {
                return response()->json([
                    'success' => false,
                    'message' => 'User tidak terautentikasi'
                ], 401);
            }

            $user = Auth::user();

            // Cek jika user adalah super admin
            if ($user->role !== 'super admin') {
                return response()->json([
                    'success' => false,
                    'message' => 'Hanya Super Admin yang dapat melakukan backup database'
                ], 403);
            }

            $database = config('database.connections.mysql.database');
            $timestamp = Carbon::now()->format('Y-m-d_H-i-s');
            $filename = "backup_{$database}_{$timestamp}.sql";
            $backupPath = storage_path("app/backups/{$filename}");

            // Ensure backup directory exists
            if (!file_exists(storage_path('app/backups'))) {
                mkdir(storage_path('app/backups'), 0755, true);
            }

            // Generate SQL content
            $sqlContent = $this->generateBackup();

            // Save the backup file to storage
            file_put_contents($backupPath, $sqlContent);

            // Log the export activity
            \App\Models\ActivityModel::create([
                'id_user' => $user->id_user,
                'description' => "Membuat backup database: {$filename}",
                'model_type' => 'Database',
                'type' => 'export',
                'id_model' => null,
                'id_cabang' => null,
                'old_data' => null,
                'new_data' => null
            ]);

            // Return response sebagai file download
            return Response::make($sqlContent, 200, [
                'Content-Type' => 'application/sql',
                'Content-Disposition' => 'attachment; filename="' . $filename . '"',
                'Content-Length' => strlen($sqlContent),
            ]);

        } catch (\Exception $e) {
            Log::error('Backup error: ' . $e->getMessage());

            return response()->json([
                'success' => false,
                'message' => 'Terjadi kesalahan saat backup database',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    private function generateBackup()
    {
        $database = config('database.connections.mysql.database');
        $user = Auth::user();

        $output = "-- Database Backup Generated on " . Carbon::now()->toDateTimeString() . "\n";
        $output .= "-- Database: {$database}\n";
        $output .= "-- Generated by: " . ($user->nama ?? $user->name ?? 'Unknown') . "\n";
        $output .= "-- Method: Manual Export\n\n";

        $output .= "SET FOREIGN_KEY_CHECKS=0;\n";
        $output .= "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n";
        $output .= "SET AUTOCOMMIT = 0;\n";
        $output .= "START TRANSACTION;\n";
        $output .= "SET time_zone = \"+00:00\";\n\n";

        // Get all tables
        $tables = DB::select('SHOW TABLES');

        foreach ($tables as $table) {
            $tableName = $table->{'Tables_in_' . $database};

            // Skip migrations table (optional)
            if ($tableName === 'migrations') {
                continue;
            }

            // Drop table if exists
            $output .= "DROP TABLE IF EXISTS `{$tableName}`;\n";

            // Get create table statement
            $createTable = DB::select("SHOW CREATE TABLE `{$tableName}`")[0];
            $output .= $createTable->{'Create Table'} . ";\n\n";

            // Get table data
            $rows = DB::table($tableName)->get();

            if ($rows->count() > 0) {
                $output .= "-- Data for table: {$tableName}\n";
                $output .= "INSERT INTO `{$tableName}` VALUES\n";

                $insertStatements = [];
                foreach ($rows as $row) {
                    $values = [];
                    foreach ((array)$row as $value) {
                        if ($value === null) {
                            $values[] = 'NULL';
                        } else {
                            $values[] = "'" . addslashes($value) . "'";
                        }
                    }
                    $insertStatements[] = "(" . implode(', ', $values) . ")";
                }

                $output .= implode(",\n", $insertStatements) . ";\n\n";
            }
        }

        $output .= "SET FOREIGN_KEY_CHECKS=1;\n";
        $output .= "COMMIT;\n";

        return $output;
    }

    public function importDatabase(Request $request)
    {
        try {
            // Check if user is authenticated
            if (!Auth::check()) {
                return response()->json([
                    'success' => false,
                    'message' => 'User tidak terautentikasi'
                ], 401);
            }

            $user = Auth::user();

            // Check if user is super admin
            if ($user->role !== 'super admin') {
                return response()->json([
                    'success' => false,
                    'message' => 'Hanya Super Admin yang dapat melakukan import database'
                ], 403);
            }

            // Validate the uploaded file
            $validator = Validator::make($request->all(), [
                'backup_file' => 'required|file|mimes:sql,txt|max:102400' // 100MB max
            ]);

            if ($validator->fails()) {
                return response()->json([
                    'success' => false,
                    'message' => 'File tidak valid',
                    'errors' => $validator->errors()
                ], 422);
            }

            // Get the uploaded file
            $backupFile = $request->file('backup_file');
            $originalName = $backupFile->getClientOriginalName();

            // Read SQL content from uploaded file
            $sqlContent = file_get_contents($backupFile->getRealPath());

            // Validate SQL content
            if (empty($sqlContent)) {
                return response()->json([
                    'success' => false,
                    'message' => 'File backup kosong atau tidak dapat dibaca'
                ], 422);
            }

            // Execute the import
            $this->executeImport($sqlContent);

            // Log the import activity
            \App\Models\ActivityModel::create([
                'id_user' => $user->id_user,
                'description' => "Import database dari file: {$originalName}",
                'model_type' => 'Database',
                'type' => 'import',
                'id_model' => null,
                'id_cabang' => null,
                'old_data' => null,
                'new_data' => null
            ]);

            return response()->json([
                'success' => true,
                'message' => 'Database berhasil diimport!',
                'file_name' => $originalName
            ]);

        } catch (\Exception $e) {
            Log::error('Import error: ' . $e->getMessage());

            return response()->json([
                'success' => false,
                'message' => 'Terjadi kesalahan saat import database',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Execute the SQL import
     */
    private function executeImport($sqlContent)
    {
        // Disable foreign key checks to avoid constraint errors during import
        DB::statement('SET FOREIGN_KEY_CHECKS=0');

        // Split SQL content into individual statements
        $statements = $this->splitSqlStatements($sqlContent);

        foreach ($statements as $statement) {
            $statement = trim($statement);

            // Skip empty statements and comments
            if (empty($statement) || strpos($statement, '--') === 0) {
                continue;
            }

            try {
                // Execute each SQL statement
                DB::statement($statement);
            } catch (\Exception $e) {
                // Re-enable foreign key checks before throwing error
                DB::statement('SET FOREIGN_KEY_CHECKS=1');
                throw new \Exception("Gagal mengeksekusi perintah SQL: " . $e->getMessage());
            }
        }

        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1');
    }

    /**
     * Split SQL content into individual statements
     */
    private function splitSqlStatements($sqlContent)
    {
        // Remove MySQL comments
        $sqlContent = preg_replace('/--.*$/m', '', $sqlContent);

        // Split by semicolon, but ignore semicolons within quotes
        $statements = [];
        $current = '';
        $inString = false;
        $stringChar = '';

        for ($i = 0; $i < strlen($sqlContent); $i++) {
            $char = $sqlContent[$i];

            if (($char === "'" || $char === '"') && ($i === 0 || $sqlContent[$i - 1] !== '\\')) {
                if (!$inString) {
                    $inString = true;
                    $stringChar = $char;
                } elseif ($inString && $stringChar === $char) {
                    $inString = false;
                }
            }

            if ($char === ';' && !$inString) {
                $statements[] = trim($current);
                $current = '';
            } else {
                $current .= $char;
            }
        }

        // Add the last statement if any
        if (!empty(trim($current))) {
            $statements[] = trim($current);
        }

        return array_filter($statements);
    }

    /**
     * Get list of available backups
     */
    public function listBackups()
    {
        try {
            if (!Auth::check() || Auth::user()->role !== 'super admin') {
                return response()->json([
                    'success' => false,
                    'message' => 'Unauthorized'
                ], 403);
            }

            $backupDir = storage_path('app/backups');
            $backups = [];

            if (file_exists($backupDir)) {
                $files = scandir($backupDir);

                foreach ($files as $file) {
                    if ($file !== '.' && $file !== '..' && pathinfo($file, PATHINFO_EXTENSION) === 'sql') {
                        $filePath = $backupDir . '/' . $file;
                        $backups[] = [
                            'name' => $file,
                            'size' => filesize($filePath),
                            'modified' => date('Y-m-d H:i:s', filemtime($filePath)),
                            'path' => $filePath
                        ];
                    }
                }

                // Sort by modification time (newest first)
                usort($backups, function($a, $b) {
                    return strtotime($b['modified']) - strtotime($a['modified']);
                });
            }

            return response()->json([
                'success' => true,
                'data' => $backups
            ]);

        } catch (\Exception $e) {
            Log::error('List backups error: ' . $e->getMessage());

            return response()->json([
                'success' => false,
                'message' => 'Gagal mengambil daftar backup',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Delete a backup file
     */
    public function deleteBackup(Request $request, $filename)
    {
        try {
            // Check if user is authenticated
            if (!Auth::check()) {
                return response()->json([
                    'success' => false,
                    'message' => 'User tidak terautentikasi'
                ], 401);
            }

            $user = Auth::user();

            // Check if user is super admin
            if ($user->role !== 'super admin') {
                return response()->json([
                    'success' => false,
                    'message' => 'Hanya Super Admin yang dapat menghapus backup'
                ], 403);
            }

            // Validate filename to prevent directory traversal
            if (!preg_match('/^backup_.*\.sql$/', $filename)) {
                return response()->json([
                    'success' => false,
                    'message' => 'Nama file backup tidak valid'
                ], 422);
            }

            $backupPath = storage_path("app/backups/{$filename}");

            // Check if file exists
            if (!file_exists($backupPath)) {
                return response()->json([
                    'success' => false,
                    'message' => 'File backup tidak ditemukan'
                ], 404);
            }

            // Delete the file
            if (unlink($backupPath)) {
                // Log the delete activity
                \App\Models\ActivityModel::create([
                    'id_user' => $user->id_user,
                    'description' => "Menghapus backup database: {$filename}",
                    'model_type' => 'Database',
                    'type' => 'delete',
                    'id_model' => null, // Since we made it nullable
                    'id_cabang' => null,
                    'old_data' => null,
                    'new_data' => null
                ]);

                return response()->json([
                    'success' => true,
                    'message' => 'Backup berhasil dihapus!',
                    'deleted_file' => $filename
                ]);
            } else {
                throw new \Exception('Gagal menghapus file backup');
            }

        } catch (\Exception $e) {
            Log::error('Delete backup error: ' . $e->getMessage());

            return response()->json([
                'success' => false,
                'message' => 'Terjadi kesalahan saat menghapus backup',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
